### ISSUE TITLE
Update vulnerable version of junit 4.12 > 4.13.1

### ISSUE THREAD

**Issue by chris-orchard** [dwp/nino-format-validation#4]
Snyk is warning me that nino-validation introduces a vulnerable version of junit (4.12):
> Introduced through: Snyk_IA_API@local › uk.gov.dwp.regex:nino-validation@1.3.0 › junit:junit@4.12

More details on the issue are here:
https://security.snyk.io/vuln/SNYK-JAVA-JUNIT-1017047

There is already an open pull request from snyk-bot with the update to junit4.13.1 that should resolve this:
https://github.com/dwp/nino-format-validation/pull/3

Can you merge this and release a new version of nino-validation please?

**Comment by HealthPDU** [comment]
covered off in 1.3.1
